/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2f3034",
        "on-secondary-container": "#b7b5b4",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-dim": "#121317",
        "on-error": "#690005",
        "on-secondary": "#313030",
        "on-surface-variant": "#d1d1d1",
        "on-secondary-fixed": "#1c1b1b",
        "tertiary-container": "#929090",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#2d2d2d",
        "on-primary-fixed": "#ffffff",
        "surface-container": "#1a1a1a",
        "on-tertiary-fixed": "#1b1c1c",
        "on-primary-container": "#ffffff",
        "secondary": "#c8c6c5",
        "error": "#ffb4ab",
        "surface-container-high": "#292a2e",
        "surface-container-highest": "#343539",
        "background": "#000000",
        "primary-container": "#ff5540",
        "inverse-primary": "#c00100",
        "on-error-container": "#ffdad6",
        "primary": "#ff5540",
        "on-tertiary": "#303030",
        "tertiary-fixed-dim": "#c8c6c6",
        "surface-container-low": "#121317",
        "surface": "#000000",
        "secondary-fixed": "#e5e2e1",
        "tertiary-fixed": "#e4e2e1",
        "on-tertiary-fixed-variant": "#474747",
        "on-primary": "#ffffff",
        "surface-bright": "#38393d",
        "inverse-surface": "#e3e2e7",
        "outline": "#474746",
        "primary-fixed-dim": "#ffb4a8",
        "error-container": "#93000a",
        "on-background": "#e3e2e7",
        "surface-tint": "#ffb4a8",
        "secondary-container": "#474746",
        "surface-container-lowest": "#000000",
        "surface-variant": "#2d2d2d",
        "on-surface": "#ffffff",
        "on-tertiary-container": "#2a2a2a",
        "primary-fixed": "#ffdad4",
        "tertiary": "#c8c6c6",
        "on-primary-fixed-variant": "#930100",
        "brand-red": "#FF0000",
        "brand-grey-light": "#b7b5b4",
        "brand-grey-dark": "#1e1f23"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin-mobile": "20px",
        "base": "8px",
        "container-margin-desktop": "48px",
        "section-gap": "80px",
        "gutter": "24px"
      },
      fontFamily: {
        "display": ["Bebas Neue", "sans-serif"],
        "body": ["Inter", "Montserrat", "sans-serif"]
      }
    },
  },
  plugins: [],
}
